'use client';
import {useState,useEffect} from 'react';
const projects=[
['01','2026 — PRESENT','GENOMICS / DEEP LEARNING','Deep Evolutionary Regulatory Transformer','跨物种调控表征学习','Exploring multimodal genomic signal tracks to learn latent regulatory states and support functional interpretation across species.','通过多模态基因组信号轨道学习潜在调控状态，探索跨物种基因组功能解释。','Ongoing · preliminary experiments','进行中 · 初步实验','Research project started in February 2026. The current focus is training a regulatory representation model from multimodal genomic signals.','2026 年 2 月开始的研究项目，目前聚焦于利用多模态基因组信号训练调控表征模型。'],
['02','2024 — 2025','miRNA / DRUG MECHANISMS','Biological regulation as a learning prior','以生物调控信息改善药物机制建模','Investigating how miRNA features connect causal pathway reconstruction and mechanism-of-action prediction, with a focus on generalization.','研究 miRNA 特征如何连接因果通路重建与药物作用机制预测，关注生物调控信息对泛化能力的影响。','Research project','研究项目','miRNA Features Drive Cross-Task Improvements in Drug Mechanistic Modeling. Evaluating intermediate regulatory layers as biological regularization across two tasks (October 2024–December 2025).','项目：miRNA Features Drive Cross-Task Improvements in Drug Mechanistic Modeling。通过因果通路重建和作用机制预测，评估中间调控层的生物正则化作用（2024.10–2025.12）。'],
['03','2025','SYNTHETIC BIOLOGY / iGEM','Engineering logic into living systems','面向抗癌应用的 AND 门基因回路','Dry-lab modeling of an AND-gate genetic circuit in E. coli, from plasmid expression and bacterial metabolism to anticancer efficacy.','作为核心干实验成员，设计大肠杆菌 AND 门质粒系统，建立表达动力学、细菌代谢与抗癌效果的计算模型。','iGEM 2025 · Gold medal','iGEM 2025 · 金奖','Core dry-lab contributor, April–October 2025. Led modeling and plasmid design with SnapGene; contributed to the project website and technical content architecture.','核心干实验成员（2025.04–2025.10）。使用 SnapGene 主导质粒系统设计与建模，并参与项目网站开发与技术内容架构。'],
['04','2025','COMPUTER VISION / APPLIED ML','From food images to nutritional insight','从食物识别到营养分析','An improved YOLOv5 pipeline trained on a self-curated cafeteria image dataset, with lightweight deployment for nutrition-oriented analysis.','构建食堂食物图像数据集，训练改进的 YOLOv5 模型，并实现面向营养分析的轻量化部署。','Course project','课程项目','Completed in December 2025. Combined dataset curation, object detection, and lightweight deployment for food recognition and nutritional analysis.','2025 年 12 月完成，整合数据集构建、目标检测与轻量化部署，用于食物识别及营养分析。']];
const awards=[['2025','iGEM Competition','Gold medal','国际遗传工程机器大赛 · 金奖'],['2023–25','Dean’s List','School of Medicine, CUHK-Shenzhen','香港中文大学（深圳）医学院 · 院长嘉许名单'],['2022','Chinese Biology Olympiad','Silver medal','全国中学生生物学竞赛 · 银牌'],['2024','Mathematical Contest in Modeling','Provincial second prize','全国大学生数学建模竞赛 · 省级二等奖'],['2023–26','Full Entrance Scholarship','CUHK-Shenzhen','香港中文大学（深圳） · 全额入学奖学金'],['2025–26','Undergraduate Research Award','CUHK-Shenzhen','香港中文大学（深圳） · 本科生科研奖励']];
function Network(){const nodes=Array.from({length:48},(_,i)=>{const a=i*2.39996,r=34+Math.sqrt(i/48)*175;return{x:Number((250+Math.cos(a)*r).toFixed(4)),y:Number((230+Math.sin(a)*r).toFixed(4))}});return <div className="network"><div className="diagram-label"><span className="dot"/>COMPUTATIONAL BIOLOGY</div><svg viewBox="0 0 500 470" role="img" aria-label="Conceptual regulatory network"><g className="orbit">{nodes.map((p,i)=>nodes.slice(i+1).map((q,j)=>Math.hypot(p.x-q.x,p.y-q.y)<92?<line key={`${i}-${j}`} x1={p.x} y1={p.y} x2={q.x} y2={q.y}/>:null))}{nodes.map((p,i)=><circle key={i} cx={p.x} cy={p.y} r={i%7===0?5:2.6} className={i%7===0?'hub':''} style={{animationDelay:`${i*.17}s`}}/>)}</g><circle cx="250" cy="230" r="211" className="guide"/><path className="guide" d="M20 230H480M250 0V460"/></svg><div className="diagram-footer"><span>SEQUENCE → REGULATION → FUNCTION</span><span>FIG. 01 / CONCEPT</span></div></div>}
export default function Home(){const[zh,setZh]=useState(false);const t=(en:string,cn:string)=>zh?cn:en;useEffect(()=>{document.documentElement.lang=zh?'zh-CN':'en'},[zh]);return <><a className="skip" href="#main">Skip to content</a><header><a className="wordmark" href="#">XC<span> / </span>Xiang Cheng</a><nav aria-label="Main navigation"><a href="#research">{t('Research','研究')}</a><a href="#about">{t('About','关于')}</a><a href="#recognition">{t('Recognition','荣誉')}</a><a href="#contact">{t('Contact','联系')}</a></nav><button className="lang" onClick={()=>setZh(!zh)} aria-label={zh?'Switch to English':'切换为中文'}>{zh?'EN ↗':'中文 ↗'}</button></header><main id="main">
<section className="hero wrap"><div><div className="eyebrow"><span className="dot"/>{t('BIOINFORMATICS · CUHK-SHENZHEN','生物信息学 · 香港中文大学（深圳）')}</div><h1>Xiang Cheng<span>程翔</span></h1><h2>{t('Learning the language','以计算理解')}<br/><em>{t('of living systems.','生命系统的语言。')}</em></h2><p>{t('I study biological regulation through the lens of machine learning — connecting genomic signals, molecular mechanisms, and computational models.','我关注机器学习与生物调控的交汇，以计算模型连接基因组信号与分子机制。')}</p><div className="hero-links"><a className="primary" href="#research">{t('Explore my research','探索我的研究')} ↗</a><a className="text-link" href="CV_Xiang_Cheng.pdf" target="_blank" rel="noreferrer">{t('Curriculum vitae','个人简历')} ↓</a></div><div className="affiliation">{t('Undergraduate researcher','本科生研究者')}<span>2023 — 2027</span></div></div><Network/></section>
<div className="topic-strip"><div className="wrap"><span>GENE REGULATION</span><i>✳</i><span>MACHINE LEARNING</span><i>✳</i><span>COMPUTATIONAL BIOLOGY</span></div></div>
<section className="wrap section" id="research"><div className="section-heading"><div><div className="eyebrow">01 / {t('RESEARCH','研究')}</div><h2>{t('Questions I’m exploring.','正在探索的问题。')}</h2></div><p>{t('From regulatory representations to engineered biological systems.','从调控表征，到工程化生物系统。')}</p></div><div className="projects">{projects.map(p=><article className="project" key={p[0]}><div className="project-index">{p[0]}<span>↗</span></div><div><div className="project-meta"><span>{p[2]}</span><span>{p[1]}</span></div><h3>{p[zh?4:3]}</h3><p>{p[zh?6:5]}</p><div className="project-bottom"><span className="status">{p[zh?8:7]}</span><details><summary>{t('Project notes','项目介绍')} <span>+</span></summary><p>{p[zh?10:9]}</p></details></div></div></article>)}</div></section>
<section className="about-section" id="about"><div className="wrap about-grid"><div><div className="eyebrow">02 / {t('BACKGROUND','学术背景')}</div><h2>{t('Biology asks.','生物学提出问题。')}<br/><em>{t('Computation connects.','计算建立联系。')}</em></h2><p>{t('I’m a Bioinformatics undergraduate at The Chinese University of Hong Kong, Shenzhen, with an exchange and visiting experience at UC Berkeley. My work spans regulatory genomics, drug mechanism modeling, and synthetic biology.','我就读于香港中文大学（深圳）生物信息学专业，曾赴加州大学伯克利分校交换与访学。研究兴趣涵盖调控基因组学、药物机制建模与合成生物学。')}</p><div className="skills">{['Python','R','Linux','Git','Machine learning','Molecular biology'].map(s=><span key={s}>{s}</span>)}</div></div><div className="education"><article><span className="date">2023 — 2027 {t('(EXPECTED)','（预计）')}</span><h3>{t('The Chinese University of Hong Kong, Shenzhen','香港中文大学（深圳）')}</h3><p>{t('Bioinformatics · School of Medicine','医学院 · 生物信息学本科')}</p><div className="grades"><div><strong>3.745<span>/4.0</span></strong><small>CGPA</small></div><div><strong>3.84<span>/4.0</span></strong><small>MAJOR GPA</small></div><div><strong>10<span>%</span></strong><small>{t('TOP IN SCHOOL','学院排名前')}</small></div></div></article><article><span className="date">JAN — MAY 2026</span><h3>{t('University of California, Berkeley','加州大学伯克利分校')}</h3><p>{t('Exchange & visiting student','交换与访问学生')}</p></article></div></div></section>
<section className="wrap section" id="recognition"><div className="section-heading"><div><div className="eyebrow">03 / {t('RECOGNITION','荣誉奖励')}</div><h2>{t('Along the way.','求索途中的印记。')}</h2></div></div><div className="awards">{awards.map(a=><div className="award" key={a[1]}><span className="date">{a[0]}</span><div><h3>{zh?a[3]:a[1]}</h3>{!zh&&<p>{a[2]}</p>}</div><span className="star">✧</span></div>)}</div></section>
<footer id="contact"><div className="wrap"><div className="eyebrow">04 / {t('GET IN TOUCH','联系')}</div><div className="contact-row"><h2>{t('Let’s connect ideas.','让想法产生连接。')}</h2><a href="mailto:123090064@link.cuhk.edu.cn" className="email">123090064@link.cuhk.edu.cn ↗</a></div><div className="footer-bottom"><span>© 2026 Xiang Cheng · 程翔</span><a href="https://github.com/XiangCheng66" target="_blank" rel="noreferrer">GitHub ↗</a><a href="#">{t('Back to top','返回顶部')} ↑</a></div></div></footer></main></>}


